### ISSUE TITLE
y-axis ticks not rounded correctly for small step quantities

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-webview-prototype#12]
see the screenshot
![Screenshot_2020-02-06_17-41-39](https://user-images.githubusercontent.com/9112758/73958352-1b9c1000-4908-11ea-82e5-9e2e33895023.png)

**Comment by Quimoniz** [comment]
Replikations-Link: https://igel.metricq.zih.tu-dresden.de/lars/#/~(cntr~(~'elab.diana.current~'elab.apollo.current)~start~1581007128000~stop~1581007227000~type~'default~pixels~3)
